Some bug fixes
FaustVX/BigFloat pull request #4
Opened 2021-01-11 17:59 UTC by DerGuru

2021-01-11 21:48 UTC, FaustVX requested changes

2021-01-11 21:48 UTC, FaustVX commented on BigFloat.cs
> +        //[Obsolete("Use BigFloat.Parse instead.")]
The Obsolete attribute can now be removed
```suggestion
```

2021-01-11 22:08 UTC, FaustVX approved these changes

2021-01-11 22:10 UTC, FaustVX approved these changes

2021-01-11 22:20 UTC, merged

2021-01-11 22:22 UTC, FaustVX commented
I've updated the NuGet package
[NuGet](https://www.nuget.org/packages/BigFloat/1.2.0)

2021-01-12 02:41 UTC, DerGuru commented
Thank you very much...
I am currently working on something to convert Units of Speed, Mass, Distance, .... and there are quite a lot of numbers very big or very small. And yards, feet, inch to the metric system takes quite a lot of precision.

2021-01-12 02:48 UTC, FaustVX commented
Ah ok,
I already tried to do this in the past, and yes, the interval can be huge.

But thanks to you for providing update for Big Float :)